// AUTO-GENERATED by scripts/gen-hashes.ts at release time. Do not edit by hand.
// Maps "<goos>_<goarch>" to the release asset filename and its SHA-256.
import type { ReleaseAsset } from "./checksums";

export const VERSION = "0.1.7";

export const RELEASES: Record<string, ReleaseAsset> = {
  "linux_amd64": { file: "datamitsu_0.1.7_linux_amd64.tar.gz", sha256: "475d500deabe83a39df5192b5f563e33d0d26144bc48a0fb581e629a886651b8" },
  "linux_arm64": { file: "datamitsu_0.1.7_linux_arm64.tar.gz", sha256: "9ba64e22c92adc2df838b5ecc3b89ffcd90ed62af1234135b71697cea31899b9" },
  "darwin_amd64": { file: "datamitsu_0.1.7_darwin_amd64.tar.gz", sha256: "bd7030040081c3513d0ebf26b6aceed2e868c56f35bf29b9e7fe60118e1d0563" },
  "darwin_arm64": { file: "datamitsu_0.1.7_darwin_arm64.tar.gz", sha256: "fc250124213fcedff47fd7b15002ab0cda14ad3ee710510bfbae7cd133a633bb" },
  "windows_amd64": { file: "datamitsu_0.1.7_windows_amd64.zip", sha256: "ded998072059d6639397420b9253824926db1f36270a557df0958f1a46e1fe66" },
  "windows_arm64": { file: "datamitsu_0.1.7_windows_arm64.zip", sha256: "49a2278145b1ca8501f7e3d1d591f27c1f3cc20f66b9591425b08fda6920575b" },
};
